services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: hexagonal
      MYSQL_USER: hexuser
      MYSQL_PASSWORD: hexpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    build: .
    environment:
      DB_URL: jdbc:mysql://db:3306/hexagonal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: hexuser
      DB_PASSWORD: hexpass
      PORT: 8080
      JWT_SECRET: change-this-in-prod-123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
